"""
Polymarket Trading Agent for 5-Minute Markets
==============================================
A modular trading bot that monitors and trades on Polymarket's 5-minute prediction markets.
"""

import asyncio
import copy
import logging
import os
import signal as _signal
from collections import deque
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Any, Tuple
import json
from dataclasses import dataclass, field
from enum import Enum
import aiohttp
import time


# ============================================================================
# Configuration & Data Models
# ============================================================================

class OrderSide(Enum):
    BUY = "BUY"
    SELL = "SELL"


class MarketStatus(Enum):
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"
    RESOLVED = "RESOLVED"


@dataclass
class Position:
    """Current position in a market"""
    market_id: str
    outcome: str
    shares: float
    avg_price: float
    current_price: float
    unrealized_pnl: float
    timestamp: datetime


@dataclass
class Order:
    """Order to place on Polymarket"""
    market_id: str
    outcome: str
    side: OrderSide
    size: float
    price: float
    timestamp: datetime
    order_id: Optional[str] = None
    

@dataclass
class TradeSignal:
    """Trading signal generated by strategy"""
    market_id: str
    outcome: str
    action: OrderSide
    confidence: float  # 0-1
    size: float
    target_price: float
    reason: str
    timestamp: datetime


@dataclass
class MarketData:
    """5-minute market data"""
    market_id: str
    question: str
    outcomes: List[str]
    prices: Dict[str, float]  # outcome -> price
    volumes: Dict[str, float]  # outcome -> volume
    liquidity: float
    end_time: datetime
    status: MarketStatus
    last_update: datetime


# ============================================================================
# Polymarket API Client
# ============================================================================

class PolymarketClient:
    """
    Client for Polymarket API interactions
    Handles authentication, market data fetching, and order placement
    """
    
    def __init__(self, api_key: str, api_secret: str, testnet: bool = True):
        self.api_key = api_key
        self.api_secret = api_secret
        self.base_url = "https://clob.polymarket.com" if not testnet else "https://clob-testnet.polymarket.com"
        self.session: Optional[aiohttp.ClientSession] = None
        self.logger = logging.getLogger(__name__)
        
    async def __aenter__(self):
        self.session = aiohttp.ClientSession()
        return self
        
    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if self.session:
            await self.session.close()
    
    async def get_markets(self, active_only: bool = True) -> List[MarketData]:
        """Fetch all active 5-minute markets"""
        # TODO: Implement actual API call
        # This is a placeholder - you'll need to add real Polymarket API endpoints
        self.logger.info("Fetching markets from Polymarket...")
        
        # Placeholder response
        markets = []
        # Replace with actual API call:
        # async with self.session.get(f"{self.base_url}/markets", headers=self._auth_headers()) as resp:
        #     data = await resp.json()
        #     markets = self._parse_markets(data)
        
        return markets
    
    async def get_market_orderbook(self, market_id: str) -> Dict[str, Any]:
        """Get current orderbook for a market"""
        self.logger.debug(f"Fetching orderbook for {market_id}")
        # TODO: Implement actual orderbook fetch
        return {"bids": [], "asks": []}
    
    async def place_order(self, order: Order) -> Optional[str]:
        """Place an order on Polymarket"""
        self.logger.info(f"Placing order: {order}")
        
        # TODO: Implement actual order placement
        # This requires:
        # 1. Order signing with your private key
        # 2. Posting to Polymarket's CLOB API
        # 3. Handling responses and errors
        
        # Placeholder
        order_id = f"order_{int(time.time() * 1000)}"
        return order_id
    
    async def cancel_order(self, order_id: str) -> bool:
        """Cancel an existing order"""
        self.logger.info(f"Cancelling order {order_id}")
        # TODO: Implement
        return True
    
    async def get_positions(self) -> List[Position]:
        """Get current open positions"""
        self.logger.debug("Fetching positions")
        # TODO: Implement
        return []
    
    def _auth_headers(self) -> Dict[str, str]:
        """Generate authenticated request headers"""
        # TODO: Implement proper authentication
        return {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }


# ============================================================================
# Trading Strategies
# ============================================================================

@dataclass
class PriceSnapshot:
    """Lightweight price snapshot — replaces deepcopy of full MarketData"""
    market_id: str
    prices: Dict[str, float]
    last_update: datetime


class BaseStrategy:
    """Base class for trading strategies"""

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.logger = logging.getLogger(__name__)
        # deque(maxlen=30) auto-evicts old entries — no manual slicing, O(1) append
        self.market_history: Dict[str, deque] = {}

    def update_market_data(self, market: MarketData):
        """Store a lightweight price snapshot — avoids deepcopy overhead"""
        if market.market_id not in self.market_history:
            self.market_history[market.market_id] = deque(maxlen=30)
        self.market_history[market.market_id].append(
            PriceSnapshot(
                market_id=market.market_id,
                prices=dict(market.prices),   # shallow copy — only the dict
                last_update=market.last_update,
            )
        )
    
    def generate_signals(self, markets: List[MarketData]) -> List[TradeSignal]:
        """Generate trading signals - override in subclass"""
        raise NotImplementedError


class MomentumStrategy(BaseStrategy):
    """
    Simple momentum strategy for 5-minute markets
    - Buys when price is rising quickly
    - Sells when price is falling quickly
    """
    
    def generate_signals(self, markets: List[MarketData]) -> List[TradeSignal]:
        signals = []
        
        for market in markets:
            self.update_market_data(market)
            
            # Need at least 3 data points for momentum
            if len(self.market_history.get(market.market_id, [])) < 3:
                continue
            
            history = self.market_history[market.market_id]
            
            for outcome in market.outcomes:
                signal = self._check_momentum(market, outcome, history)
                if signal:
                    signals.append(signal)
        
        return signals
    
    def _check_momentum(self, market: MarketData, outcome: str,
                       history) -> Optional[TradeSignal]:
        """Check if there's momentum signal for this outcome"""

        prices = [s.prices.get(outcome, 0.0) for s in history][-5:]

        if len(prices) < 3:
            return None

        base = prices[-3]
        recent_change = (prices[-1] - base) / base if base > 0 else 0.0
        
        # Thresholds from config
        buy_threshold = self.config.get('momentum_buy_threshold', 0.05)  # 5% rise
        sell_threshold = self.config.get('momentum_sell_threshold', -0.05)  # 5% fall
        min_confidence = self.config.get('min_confidence', 0.6)
        
        # Generate signals
        if recent_change > buy_threshold:
            confidence = min(0.9, 0.5 + abs(recent_change) * 5)
            if confidence >= min_confidence:
                return TradeSignal(
                    market_id=market.market_id,
                    outcome=outcome,
                    action=OrderSide.BUY,
                    confidence=confidence,
                    size=self._calculate_position_size(confidence),
                    target_price=prices[-1] * 1.01,  # Slight premium
                    reason=f"Momentum buy: {recent_change:.1%} price increase",
                    timestamp=datetime.now()
                )
        
        elif recent_change < sell_threshold:
            confidence = min(0.9, 0.5 + abs(recent_change) * 5)
            if confidence >= min_confidence:
                return TradeSignal(
                    market_id=market.market_id,
                    outcome=outcome,
                    action=OrderSide.SELL,
                    confidence=confidence,
                    size=self._calculate_position_size(confidence),
                    target_price=prices[-1] * 0.99,  # Slight discount
                    reason=f"Momentum sell: {recent_change:.1%} price decrease",
                    timestamp=datetime.now()
                )
        
        return None
    
    def _calculate_position_size(self, confidence: float) -> float:
        """Calculate position size based on confidence"""
        base_size = self.config.get('base_position_size', 10.0)  # $10 base
        max_size = self.config.get('max_position_size', 100.0)   # $100 max
        
        # Scale with confidence
        size = base_size * (1 + confidence)
        return min(size, max_size)


# ============================================================================
# Risk Management
# ============================================================================

class RiskManager:
    """
    Manages risk limits and position sizing
    - Maximum position size per market
    - Maximum total exposure
    - Stop loss enforcement
    - Daily loss limits
    """
    
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.logger = logging.getLogger(__name__)
        self.daily_pnl = 0.0
        self.daily_start = datetime.now().date()
        
    def check_order(self, order: Order, current_positions: List[Position]) -> Tuple[bool, str]:
        """Check if order passes risk limits. Returns (approved, reason)."""

        # Check daily loss limit
        max_daily_loss = self.config.get('max_daily_loss', 500.0)
        if self.daily_pnl < -max_daily_loss:
            return False, f"Daily loss limit reached: ${abs(self.daily_pnl):.2f}"

        # Check position size
        max_position = self.config.get('max_position_size', 100.0)
        if order.size > max_position:
            return False, f"Order size ${order.size:.2f} exceeds max ${max_position:.2f}"

        # Build index once — O(n) once instead of O(n) per lookup
        total_exposure = 0.0
        market_exposure = 0.0
        for p in current_positions:
            value = p.shares * p.current_price
            total_exposure += value
            if p.market_id == order.market_id:
                market_exposure += value

        max_exposure = self.config.get('max_total_exposure', 1000.0)
        if total_exposure + order.size > max_exposure:
            return False, f"Total exposure would exceed limit: ${total_exposure + order.size:.2f} > ${max_exposure:.2f}"

        max_per_market = self.config.get('max_per_market', 200.0)
        if market_exposure + order.size > max_per_market:
            return False, f"Market exposure limit: ${market_exposure + order.size:.2f} > ${max_per_market:.2f}"

        return True, "OK"

    def update_daily_pnl(self, pnl: float):
        """Update daily P&L — uses single timestamp to avoid midnight race"""
        today = datetime.utcnow().date()   # UTC — no timezone drift on cloud instances
        if today > self.daily_start:
            self.daily_pnl = 0.0
            self.daily_start = today
        self.daily_pnl += pnl
        self.logger.info(f"Daily P&L: ${self.daily_pnl:.2f}")


# ============================================================================
# Main Trading Agent
# ============================================================================

class PolymarketAgent:
    """
    Main trading agent that coordinates all components
    """
    
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.logger = self._setup_logging()
        
        # Initialize components
        self.client = PolymarketClient(
            api_key=config['api_key'],
            api_secret=config['api_secret'],
            testnet=config.get('testnet', True)
        )
        
        # Choose strategy
        strategy_name = config.get('strategy', 'momentum')
        if strategy_name == 'momentum':
            self.strategy = MomentumStrategy(config.get('strategy_config', {}))
        else:
            raise ValueError(f"Unknown strategy: {strategy_name}")
        
        self.risk_manager = RiskManager(config.get('risk_config', {}))
        
        # State
        self.running = False
        self.positions: List[Position] = []
        self.pending_orders: List[Order] = []
        
    def _setup_logging(self) -> logging.Logger:
        """Setup logging configuration"""
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
            handlers=[
                logging.FileHandler('polymarket_agent.log'),
                logging.StreamHandler()
            ]
        )
        return logging.getLogger(__name__)
    
    async def start(self):
        """Start the trading agent"""
        self.logger.info("=" * 80)
        self.logger.info("Starting Polymarket Trading Agent")
        self.logger.info("=" * 80)
        self.logger.info(f"Strategy: {self.config.get('strategy')}")
        self.logger.info(f"Testnet: {self.config.get('testnet', True)}")
        self.logger.info(f"Update interval: {self.config.get('update_interval_seconds', 10)}s")
        
        self.running = True
        
        async with self.client:
            while self.running:
                try:
                    await self._trading_loop()
                    await asyncio.sleep(self.config.get('update_interval_seconds', 10))
                except Exception as e:
                    self.logger.error(f"Error in trading loop: {e}", exc_info=True)
                    await asyncio.sleep(5)
    
    async def _trading_loop(self):
        """Main trading loop iteration"""
        
        # 1. Fetch current markets
        markets = await self.client.get_markets()
        self.logger.info(f"Monitoring {len(markets)} markets")
        
        # 2. Update positions
        self.positions = await self.client.get_positions()
        
        # 3. Generate trading signals
        signals = self.strategy.generate_signals(markets)
        self.logger.info(f"Generated {len(signals)} trading signals")
        
        # 4. Execute approved signals
        for signal in signals:
            await self._execute_signal(signal)
        
        # 5. Monitor and manage existing positions
        await self._manage_positions()
    
    async def _execute_signal(self, signal: TradeSignal):
        """Execute a trading signal if it passes risk checks"""
        
        # Convert signal to order
        order = Order(
            market_id=signal.market_id,
            outcome=signal.outcome,
            side=signal.action,
            size=signal.size,
            price=signal.target_price,
            timestamp=datetime.now()
        )
        
        # Risk check
        approved, reason = self.risk_manager.check_order(order, self.positions)
        
        if not approved:
            self.logger.warning(f"Order rejected: {reason}")
            return
        
        # Place order
        self.logger.info(f"Executing signal: {signal.reason}")
        order_id = await self.client.place_order(order)
        
        if order_id:
            order.order_id = order_id
            self.pending_orders.append(order)
            self.logger.info(f"Order placed: {order_id}")
        else:
            self.logger.error("Failed to place order")
    
    async def _manage_positions(self):
        """Monitor and manage existing positions"""
        
        for position in self.positions:
            # Check stop loss
            stop_loss_pct = self.config.get('risk_config', {}).get('stop_loss_pct', 0.10)
            
            if position.unrealized_pnl < -position.shares * position.avg_price * stop_loss_pct:
                self.logger.warning(f"Stop loss triggered for {position.market_id}")
                # TODO: Implement position closure
    
    async def stop(self):
        """Stop the trading agent"""
        self.logger.info("Stopping Polymarket Trading Agent...")
        self.running = False


# ============================================================================
# Entry Point
# ============================================================================

async def main():
    """Main entry point — credentials loaded from environment, never hardcoded"""

    from dotenv import load_dotenv
    load_dotenv()

    api_key    = os.environ.get('POLYMARKET_API_KEY')
    api_secret = os.environ.get('POLYMARKET_API_SECRET')

    if not api_key or not api_secret:
        raise SystemExit(
            "\n❌  Missing credentials.\n"
            "    Set POLYMARKET_API_KEY and POLYMARKET_API_SECRET in your .env file.\n"
            "    Copy .env.example → .env and fill in your testnet keys.\n"
        )

    config = {
        'api_key':    api_key,
        'api_secret': api_secret,
        'testnet':    os.environ.get('TESTNET_MODE', 'true').lower() != 'false',

        'strategy': 'momentum',
        'strategy_config': {
            'momentum_buy_threshold':  float(os.environ.get('MOMENTUM_BUY_THRESHOLD',  '0.05')),
            'momentum_sell_threshold': float(os.environ.get('MOMENTUM_SELL_THRESHOLD', '-0.05')),
            'min_confidence':          float(os.environ.get('MIN_CONFIDENCE',          '0.6')),
            'base_position_size':      float(os.environ.get('BASE_POSITION_SIZE',      '10.0')),
            'max_position_size':       float(os.environ.get('MAX_POSITION_SIZE',       '50.0')),
        },

        'risk_config': {
            'max_daily_loss':      float(os.environ.get('MAX_DAILY_LOSS',      '100.0')),
            'max_total_exposure':  float(os.environ.get('MAX_TOTAL_EXPOSURE',  '500.0')),
            'max_per_market':      float(os.environ.get('MAX_PER_MARKET',      '100.0')),
            'max_position_size':   float(os.environ.get('MAX_POSITION_SIZE',   '50.0')),
            'stop_loss_pct':       float(os.environ.get('STOP_LOSS_PCT',       '0.20')),
        },

        'update_interval_seconds': int(os.environ.get('UPDATE_INTERVAL_SECONDS', '10')),
    }

    agent = PolymarketAgent(config)
    loop  = asyncio.get_event_loop()

    # Graceful shutdown on SIGTERM / SIGINT — cancels pending orders before exit
    async def _shutdown(sig_name: str):
        logging.getLogger(__name__).info(f"Received {sig_name} — shutting down gracefully...")
        await agent.stop()

    for sig in (_signal.SIGTERM, _signal.SIGINT):
        loop.add_signal_handler(sig, lambda s=sig: asyncio.create_task(_shutdown(s.name)))

    await agent.start()


if __name__ == "__main__":
    asyncio.run(main())
