"""
Polymarket Credentials Setup
==============================
Run this ONCE after creating a Polymarket account and depositing USDC.
Derives API keys from your private key and writes them to .env.

Requirements:
  - A Polygon wallet with USDC deposited on polymarket.com
  - pip install py-clob-client==0.34.5

Usage:
  python setup_credentials.py

You will be prompted for your private key. It is NEVER saved to disk
by this script — only the derived API keys (not the private key itself)
are written to .env.
"""

import os
import sys
import getpass


def main():
    print("\n" + "="*60)
    print("  POLYMARKET CREDENTIALS SETUP")
    print("="*60)
    print()
    print("  This script will:")
    print("  1. Take your Polygon private key (not saved to disk)")
    print("  2. Derive your Polymarket API credentials from it")
    print("  3. Write the API keys to .env")
    print()
    print("  Your private key is used only to sign the derivation")
    print("  request — it is NOT stored anywhere.")
    print()

    private_key = getpass.getpass("  Enter your Polygon private key (0x...): ").strip()
    if not private_key.startswith("0x"):
        private_key = "0x" + private_key

    funder_address = input("  Enter your Polygon wallet address (0x...): ").strip()

    print()
    print("  Connecting to Polymarket CLOB...")

    try:
        from py_clob_client.client import ClobClient
    except ImportError:
        print("  ❌ py-clob-client not installed.")
        print("     Run: pip install py-clob-client==0.34.5")
        sys.exit(1)

    try:
        client = ClobClient(
            host="https://clob.polymarket.com",
            key=private_key,
            chain_id=137,
            signature_type=1,
            funder=funder_address,
        )

        print("  Deriving API credentials...")
        creds = client.create_or_derive_api_creds()

        if not creds:
            print("  ❌ Failed to derive credentials. Check your private key and address.")
            sys.exit(1)

        print(f"  ✅ Got API key: {creds.api_key[:8]}...")

        # Write .env
        env_content = f"""# Polymarket Bot Credentials
# Generated by setup_credentials.py — keep this file SECRET

POLY_PRIVATE_KEY={private_key}
POLY_API_KEY={creds.api_key}
POLY_API_SECRET={creds.api_secret}
POLY_API_PASSPHRASE={creds.api_passphrase}
POLY_FUNDER_ADDRESS={funder_address}
POLY_SIGNATURE_TYPE=1
"""
        with open(".env", "w") as f:
            f.write(env_content)

        print()
        print("  ✅ Credentials saved to .env")
        print()
        print("  Verifying connection...")
        ok = client.get_ok()
        print(f"  CLOB connection: {'✅ OK' if ok else '❌ Failed'}")

        bal = client.get_balance_allowance(params=None)
        print(f"  Balance info: {bal}")

        print()
        print("="*60)
        print("  SETUP COMPLETE")
        print("="*60)
        print()
        print("  Run the bot in dry-run mode first:")
        print("    python bot.py --dry-run --mode safe --max-trades 10")
        print()
        print("  When ready for live trading:")
        print("    python bot.py --mode safe")
        print()

    except Exception as e:
        print(f"  ❌ Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
